### ISSUE TITLE
Clearing DBs?

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/vaindock#10]
I want to drop web and raw, how can I do that?

**Comment by kvahuja** [comment]
can you not open the pgAdmin query tool and fire

```
drop schema public cascade;
create schema public;
```

once done, apigrabber and proecssor create their own tables. web i run php artisan migrate and it creates the tables.

this is what I do. are you expecting something specific which I am not getting?

**Comment by schneefux** [comment]
I'm just not that fluid with SQL. 😄 I drop'ed the tables and then they were gone because I lacked the permissions to recreate.

**Comment by kvahuja** [comment]
use the queries I mentioned :)
