### ISSUE TITLE
Fix container dependencies

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/vaindock#11]
apigrabber, processor and compiler depend on the Postgres DBs to be ready. If they start sooner than the DB is ready, they fail and die.
This can either be solved in apigrabber, processor and compiler by retrying until the connection is successful, but I think that if Docker guaranteed to have the DBs started before the applications, we would have a cleaner solution.

**Comment by kvahuja** [comment]
I will add a script at the start such that if a DB dependency is not up the script will not start.

having said that we should have logic in workers to handle the situation gracefully if a DB/service is unavailable. This is the core part of micro-services architecture. we will be fine for now i guess but long term think about this.

**Comment by kvahuja** [comment]
Docker doesn't allow this OOTB given the premise of micro-services and they don't want dependencies on containers.

We have link command in the compose that will start dependent.

I don't think we should be fixing this in docker. While I totally agree this is a convenient fix, I think it breaks our microservices premise. Like NGINX or pgAdmin as services today. they start and they don't respond but the container doesn't crash. We should have same logic in services too.

here is a script (https://github.com/vishnubob/wait-for-it) that I can implement in Docker Startup but I would rather prefer this is done in the Services (startup check).

this way we can also make sure if a DB is taken down we do not crash workers and need to restart them.

If you disagree lets discuss on Discord

**Comment by schneefux** [comment]
Agree! I opened issue on each service and on the shared library to track it.
